### ISSUE TITLE
SwipeControl: The image WebGLTile layer is offset on small screen

### ISSUE THREAD

**Issue by maxreinhart** [Viglino/ol-ext#799] opened 2022-06-20 20:55 UTC
On small laptop or on a phone, the SwipeControl does not work properly with a WebGLTile, there is like an offset.

To reproduce this, you can run the [example](https://viglino.github.io/ol-ext/examples/control/map.control.swipe.html) (using the commented GeoTIFF/WebGLTile) on a phone with the horizontal mode activated (works also with the vertical mode but I had to increase the map width to 1600px ).
![bug_swipe](https://user-images.githubusercontent.com/55090205/174675562-b7d779db-461c-4805-99a2-a6b991ad6b33.png)

**Comment by jthiard** [comment] 2022-06-21 14:31
Hi, I'm @maxreinhart's colleague. I was able to reproduce this issue when the screen pixel ratio is not 1 (phone, macbook pro, chrome dev tools in responsive mode...).

I was able to identifies those two calculations:

 - https://github.com/Viglino/ol-ext/blob/v3.2.26/src/control/Swipe.js#L318 (lower layer in horizontal swipe)
 - https://github.com/Viglino/ol-ext/blob/v3.2.26/src/control/Swipe.js#L367 (right layer in vertical swipe)

that looked wrong when pixel ratio is not 1.

Will try to set up a PR.

**Comment by Viglino** [comment] 2022-06-22 06:34
I have no error on my phone or using a chrome debug with other pixel ratio...

**Comment by Viglino** [comment] 2022-06-22 06:44
PS: You can also look at the new control `ol/control/SwipeMap` that clips the map in the DOM (but you'll have to deal with 2 maps).
See :  https://viglino.github.io/ol-ext/examples/misc/map.compare.html

**Comment by jthiard** [comment] 2022-06-28 14:04
Hi, sorry for the late response.
It may be because a refresh was needed after setting the pixel ratio in chrome dev tools.
By the way this is now fixed by #803 (thanks for merging), the [webgl example](http://viglino.github.io/ol-ext/examples/control/map.control.swipe2.html) works well and this issue can be closed!

**Closed** 2022-06-30 09:54 UTC
